MAIN    = 05_tri_counter.cpp
OTHERS  = 
LIBRARY = 
OUTPUT  = main.out

VERSION = -std=c++20
WARNING = -Wall -Wextra -Wconversion -Wsign-conversion -pedantic

all:
	g++ $(VERSION) $(LIBRARY) $(WARNING) $(OTHERS) $(MAIN) -o $(OUTPUT)
clean:
	rm main

